import '../models/pet.dart';

class PetRepository {
  static List<Pet> getPets() {
    return [
      Pet(
        id: '1',
        name: 'Buddy',
        breed: 'Golden Retriever',
        age: 3,
        price: 500.0,
        imageUrl: 'assets/golden.png',
        gender: 'M',
        description: '',
        characteristics: [],
      ), Pet(
        id: '2',
        name: 'Milo',
        breed: 'Beagle',
        age: 2,
        price: 400.0,
        imageUrl: 'assets/beagle.png',
        gender: 'F',
        description: '',
        characteristics: [],
      ), Pet(
        id: '3',
        name: 'Luna',
        breed: 'Labrador',
        age: 4,
        price: 600.0,
        imageUrl: 'assets/labrador.png',
        gender: 'M',
        description: 'Friendly and energetic',
        characteristics: [],
      ), Pet(
        id: '4',
        name: 'Max',
        breed: 'Golden Retriever',
        age: 2,
        price: 550.0,
        imageUrl: 'assets/golden.png',
        gender: 'M',
        description: '',
        characteristics: [],
      ), Pet(
        id: '5',
        name: 'Chloe',
        breed: 'Beagle',
        age: 3,
        price: 450.0,
        imageUrl: 'assets/beagle.png',
        gender: 'F',
        description: '',
        characteristics: [],
      ),
      Pet(
        id: '6',
        name: 'Rocky',
        breed: 'Labrador',
        age: 5,
        price: 650.0,
        imageUrl: 'assets/labrador.png',
        gender: 'M',
        description: '',
        characteristics: [],
      ),
      Pet(
        id: '7',
        name: 'Buddy',
        breed: 'Golden Retriever',
        age: 1,
        price: 400.0,
        imageUrl: 'assets/golden.png',
        gender: 'M',
        description: '',
        characteristics: [],
      ),
      Pet(
        id: '8',
        name: 'Bella',
        breed: 'Beagle',
        age: 4,
        price: 500.0,
        imageUrl: 'assets/beagle.png',
        gender: 'F',
        description: '',
        characteristics: [],
      ),
      Pet(
        id: '9',
        name: 'Oscar',
        breed: 'Labrador',
        age: 3,
        price: 600.0,
        imageUrl: 'assets/labrador.png',
        gender: 'M',
        description: '',
        characteristics: [],
      ),
      Pet(
        id: '10',
        name: 'Lucy',
        breed: 'Golden Retriever',
        age: 2,
        price: 550.0,
        imageUrl: 'assets/golden.png',
        gender: 'F',
        description: '',
        characteristics: [],
      ),
      Pet(
        id: '11',
        name: 'Rocky',
        breed: 'Beagle',
        age: 5,
        price: 600.0,
        imageUrl: 'assets/beagle.png',
        gender: 'M',
        description: '',
        characteristics: [],
      ),
      Pet(
        id: '12',
        name: 'Charlie',
        breed: 'Labrador',
        age: 4,
        price: 650.0,
        imageUrl: 'assets/labrador.png',
        gender: 'M',
        description: '',
        characteristics: [],
      ),
      Pet(
        id: '13',
        name: 'Max',
        breed: 'Golden Retriever',
        age: 3,
        price: 500.0,
        imageUrl: 'assets/golden.png',
        gender: 'M',
        description: '',
        characteristics: [],
      ),
      Pet(
        id: '14',
        name: 'Sadie',
        breed: 'Beagle',
        age: 2,
        price: 450.0,
        imageUrl: 'assets/beagle.png',
        gender: 'F',
        description: '',
        characteristics: [],
      ),
      Pet(
        id: '15',
        name: 'Zoe',
        breed: 'Labrador',
        age: 3,
        price: 550.0,
        imageUrl: 'assets/labrador.png',
        gender: 'F',
        description: '',
        characteristics: [],
      ),
      Pet(
        id: '16',
        name: 'Buddy',
        breed: 'Golden Retriever',
        age: 4,
        price: 600.0,
        imageUrl: 'assets/golden.png',
        gender: 'M',
        description: '',
        characteristics: [],
      ),
      Pet(
        id: '17',
        name: 'Toby',
        breed: 'Beagle',
        age: 1,
        price: 400.0,
        imageUrl: 'assets/beagle.png',
        gender: 'M',
        description: '',
        characteristics: [],
      ),
      Pet(
        id: '18',
        name: 'Trixie',
        breed: 'Labrador',
        age: 5,
        price: 650.0,
        imageUrl: 'assets/labrador.png',
        gender: 'F',
        description: '',
        characteristics: [],
      ),
      Pet(
        id: '19',
        name: 'Rex',
        breed: 'Golden Retriever',
        age: 6,
        price: 700.0,
        imageUrl: 'assets/golden.png',
        gender: 'M',
        description: '',
        characteristics: [],
      ),
      Pet(
        id: '20',
        name: 'Milo',
        breed: 'Beagle',
        age: 3,
        price: 550.0,
        imageUrl: 'assets/beagle.png',
        gender: 'F',
        description: '',
        characteristics: [],
      ),
    ];
  }
}
